### ISSUE TITLE
Missing docker-compose.yml file as per wiki

### ISSUE THREAD

**Issue by daveseff** [GriffinPlus/docker-zimbra#17]
in the Wiki document, "Deploying Zimbra with NGINX Proxy, Letsencrypt and docker compose", there is a link to the docker-compose yaml file. This link is broken.

**Comment by griffinplus-admin** [comment]
Hi @daveseff,

thank you for filing the issue. You're right, the compose file was still on the *dev* branch. I've pulled it over to the *master* branch. Have a look [here](https://github.com/GriffinPlus/docker-zimbra/tree/dev/deploy/nginx-proxy%2Bletsencrypt).

I'm sorry to say this, but we have stopped development on the Docker image as we have been using Mailcow for the actual mail server and Nextcloud with the Rainloop addon for the web frontend for quite some time. It's easier to administer, more stable and scales better. Since you seem to be looking for a groupware solution anyway, maybe that would be a way for you as well.
