### ISSUE TITLE
Starting DNS forwarder and DHCP server dnsmasq [ERROR]

### ISSUE THREAD

**Issue by legolass73** [GriffinPlus/docker-zimbra#6]
hello,
on the first launch, the container a stopped almost instantly with a log error: "dnsmasq: bad option at line 2 of /etc/dnsmasq.conf".
the second he gave me this error: "dnsmasq: setting capabilities failed: Operation not permitted"

**Comment by ravenpride** [comment]
Hello @legolass73,

The `dnsmasq.conf` is written when the container starts up. You can can see [here](https://github.com/GriffinPlus/docker-zimbra/blob/237d8420de43be5c6fc3e60d152e089ff21d403a/target/docker-entrypoint.sh#L300) what is done. In line 2 there is only a static string (`listen-address=127.0.0.1`), nothing that is crafted dynamically. So I cannot see what could be wrong with that.

The second issue concerning the capabilities is most likely caused by docker not granting enough permissions to the container. Do you use a "regular" docker host setup or do you have a Container Orchestrator (like Kubernetes) running? Please post your docker command or docker-compose file you use to bring the container up.

Thank you.

**Comment by ravenpride** [comment]
Oh, did you have a look at the [wiki](https://github.com/GriffinPlus/docker-zimbra/wiki/Deploying-Zimbra-on-Docker-Host). There is an article about configuring the container.

**Comment by legolass73** [comment]
I have of course looked at the wiki before writing an issue, however I don't have access to zimbra...

apart from writing it on the console, that's all the container does:  
* Starting DNS forwarder and DHCP server dnsmasq

   ...done.

Installing minimalistic Ubuntu 18.04 LTS (bionic)...

I: Retrieving InRelease 



Besides, I'm under synology, all my other containers work perfectly well except the ones where the configuration is missing.

**Comment by legolass73** [comment]
besides I do not see the usefulness of the dnsmasq in this container, can you explain me?

**Comment by ravenpride** [comment]
Sure, dnsmasq sets up a split-horizon DNS which responds to DNS requests issued by zimbra's processes running in the container. When a process asks for the IP address of your zimbra host (e.g. zimba.my-domain.com) dnsmasq returns the internal IP address of the container, not the external (real) IP address. Furthermore it answers the query which server is responsible for your mail domain (MX record).

On your synology, can you influence the permissions/capabilities of a container? You can also try to run the entire container in privileged mode. That includes a lot more permissions than zimbra actually needs, but could help to track the issue down.

**Comment by legolass73** [comment]
I understand much better, yes I can inflict permiision I have the option to grant administrator permissions, I do have plenty of ram, but how much is 6GB of RAM?
 Is it normal that they take so long to download everything they need?

**Comment by legolass73** [comment]
[zimbra.servais.cf.html.pdf](https://github.com/GriffinPlus/docker-zimbra/files/4437290/zimbra.servais.cf.html.pdf)

**Comment by ravenpride** [comment]
6 GB = 6 Gigabytes of RAM (memory).

Usually NAS devices do not have that much memory. Please have a look [here](http://docs.zimbra.com/docs/shared/8.6.0/system_requirements/wwhelp/wwhimpl/js/html/wwhelp.htm#href=System_Requirements_86.System_Requirements_for_Zimbra_Collaboration.html) for Zimbra's minimum requirements. They state that 8GB of RAM is required for a minimal installation, but for only a few users 6GB should suffice.

**Comment by legolass73** [comment]
ok
